# Default values for app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  # Link to your container registry. You will launch it in Yandex Cloud.
  repository: "cr.yandex/registryname/stg_service"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v2022-08-09-r2"

containerPort: 5000

config:
  KAFKA_HOST: "rc1a-alknk3mn50v42nds.mdb.yandexcloud.net"
  KAFKA_PORT: "9091"
  KAFKA_CONSUMER_USERNAME: "producer_consumer"
  KAFKA_CONSUMER_PASSWORD: "PASSWORD"
  KAFKA_CONSUMER_GROUP: "producer_consumer"
  KAFKA_SOURCE_TOPIC: "order-service_orders"
  KAFKA_DESTINATION_TOPIC: "stg-service-orders"

  
  PG_WAREHOUSE_HOST: "rc1b-iwgobjsygahrbvgf.mdb.yandexcloud.net"
  PG_WAREHOUSE_PORT: "6432"
  PG_WAREHOUSE_DBNAME: "sprint9dwh"
  PG_WAREHOUSE_USER: "user"
  PG_WAREHOUSE_PASSWORD: "PASSWORD"
  
  REDIS_HOST: "c-c9q8s4ncldmoaqir64h8.rw.mdb.yandexcloud.net"
  REDIS_PORT: "6380"
  REDIS_PASSWORD: "PASSWORD"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
